# Generated by Django 5.2 on 2025-05-07 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='logo',
            field=models.CharField(blank=True, choices=[('Adobe.svg', 'Adobe'), ('Ahrefs.svg', 'Ahrefs'), ('Airtable.svg', 'Airtable'), ('Amazon.svg', 'Amazon'), ('Apple.svg', 'Apple'), ('Asana.svg', 'Asana'), ('Calendly.svg', 'Calendly'), ('Canva.svg', 'Canva'), ('Circle.svg', 'Circle'), ('Dropbox.svg', 'Dropbox'), ('Grammarly.svg', 'Grammarly'), ('Invision.svg', 'Invision'), ('Loom.svg', 'Loom'), ('Microsoft.svg', 'Microsoft'), ('Miro.svg', 'Miro'), ('Monday.svg', 'Monday'), ('Netflix.svg', 'Netflix'), ('Patreon.svg', 'Patreon'), ('Shutterstock.svg', 'Shutterstock'), ('Sketch.svg', 'Sketch'), ('Spotify.svg', 'Spotify'), ('Webflow.svg', 'Webflow'), ('Zapier.svg', 'Zapier')], max_length=100),
        ),
        migrations.AddField(
            model_name='subscription',
            name='uploaded_logo',
            field=models.ImageField(blank=True, null=True, upload_to='uploaded_logos/'),
        ),
    ]
