# Generated by Django 5.2 on 2025-05-07 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_subscription_logo_subscription_uploaded_logo'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('paused', 'Paused'), ('canceled', 'Canceled')], default='active', max_length=20),
        ),
    ]
